server: add authorization check to User lookup endpoint in API
walmartlabs/concord pull request #1035
Opened 2024-11-12 19:40 UTC by laurayco

restricts UserResourceV2 to only allow a user to look up their own information or requires admin permissions.

2024-11-12 19:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/walmartlabs/concord?pullRequest=1035) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/walmartlabs/concord?pullRequest=1035) before we can accept your contribution.<br/><hr/>**lauren kaviak** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/walmartlabs/concord?pullRequest=1035) it.</sub>

2024-11-13 04:29 UTC, ibodrov requested changes

2024-11-13 04:29 UTC, ibodrov commented on server/impl/src/main/java/com/walmartlabs/concord/server/user/UserResourceV2.java
> +        }
Let's inline the assertAdmin method and just do `...if (!Roles.isAdmin())...` right here. And let's be more specific in the error message. In the old UserResource the assert was strict all or nothing, and here it is more complicated.

```suggestion
        if(!authenticatedId.equals(id) && !Roles.isAdmin()) {
            throw new UnauthorizedException("Users can only view their own information or must have admin privileges.");
        }
```

or something like that.

2024-11-14 17:22 UTC, brig commented on server/impl/src/main/java/com/walmartlabs/concord/server/user/UserResourceV2.java
> +
unused, I think

```suggestion
```

2024-11-19 14:04 UTC, ibodrov approved these changes

2024-11-19 15:44 UTC, merged