k8sagent support for apiextensions.k8s.io/v1 crd to support k8s 1.22+
walmartlabs/concord pull request #624
Opened 2022-07-14 05:53 UTC by ajayk

Testing
 ```agent-operator git:(agent-crdv1-changes) ✗ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/arm64"}
```

``` agent-operator git:(agent-crdv1-changes) ✗ minikube kubectl -- logs -f concord-agent-operator-55d694858d-8c2d4
05:24:04.195 [main] [INFO ] c.w.concord.agentoperator.Operator - main -> my watch begins... (namespace=default)
05:24:36.597 [scheduler-worker] [INFO ] c.w.c.a.planner.CreatePodChange - apply -> created a pod example-agentpool/example-agentpool-00000
05:25:48.015 [scheduler-worker] [INFO ] c.w.c.a.p.CreateConfigMapChange - apply -> created a configmap example-agentpool-cfg
05:25:51.306 [scheduler-worker] [INFO ] c.w.concord.agentoperator.PodUtils - ['example-agentpool-00000']: apply tag ['concordTaggedForRemoval': 'true'] -> done
05:25:58.204 [scheduler-worker] [INFO ] c.w.concord.agentoperator.PodUtils - ['example-agentpool-00000']: apply tag ['preStopHookTermination': 'true'] -> done
05:25:58.204 [scheduler-worker] [INFO ] c.w.c.a.planner.TryToDeletePodChange - apply ['example-agentpool-00000'] -> Marked for termination (former phase: Running)
05:26:04.304 [scheduler-worker] [WARN ] c.w.c.a.planner.TryToDeletePodChange - ['example-agentpool-00000'] -> has been marked for termination. Waiting for running process to complete ...
05:26:09.802 [scheduler-worker] [WARN ] c.w.c.a.planner.TryToDeletePodChange - ['example-agentpool-00000'] -> has been marked for termination. Waiting for running process to complete ...
05:26:15.387 [scheduler-worker] [WARN ] c.w.c.a.planner.TryToDeletePodChange - ['example-agentpool-00000'] -> has been marked for termination. Waiting for running process to complete ...
05:26:21.086 [scheduler-worker] [WARN ] c.w.c.a.planner.TryToDeletePodChange - ['example-agentpool-00000'] -> has been marked for termination. Waiting for running process to complete ...
05:26:26.793 [scheduler-worker] [INFO ] c.w.c.a.planner.CreatePodChange - apply -> created a pod example-agentpool/example-agentpool-00000
05:26:40.698 [scheduler-worker] [INFO ] c.w.c.a.planner.CreatePodChange - apply -> created a pod example-agentpool/example-agentpool-00000
```

```➜  agent-operator git:(agent-crdv1-changes) ✗ kubectl get crds
NAME                                 CREATED AT
agentpools.concord.walmartlabs.com   2022-07-14T05:18:13Z
➜  agent-operator git:(agent-crdv1-changes) ✗ kubectl get agentpools
NAME                AGE
example-agentpool   29m
➜  agent-operator git:(agent-crdv1-changes) ✗ kubectl get agentpool/example-agentpool
NAME                AGE
example-agentpool   29m
```

2022-07-14 05:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/walmartlabs/concord?pullRequest=624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/walmartlabs/concord?pullRequest=624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/walmartlabs/concord?pullRequest=624) it.</sub>

2022-07-14 20:00 UTC, agnewp requested changes

2022-07-18 18:13 UTC, ajayk commented on targetplatform/pom.xml
> +        <kubernetes.client.version>5.7.0</kubernetes.client.version>
Addressed in the latest commit

2022-07-18 18:14 UTC, ajayk commented on k8s/agent-operator/deploy/crds/agentpools.concord.walmartlabs.com-v1.yml
> +              configMap:
x-kubernetes-embedded-resource: true leads to unnecessary side effects on the existing operator codebase probably tackle this in the next PR

2022-07-18 21:52 UTC, ibodrov approved these changes

2022-07-18 21:52 UTC, ibodrov commented on pom.xml
> -                    <version>1.13.7</version>
I suggest that the plugin's version should be removed from this file and updated in the parent pom instead.

2022-07-20 16:54 UTC, ibodrov approved these changes

2022-07-20 16:54 UTC, merged